name: build

on:
  push:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Login registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # region debug
      - name: Get image meta
        id: debug
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/debug
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,suffix=-${{ github.run_number }},event=branch
            type=ref,suffix=-${{ github.run_number }},event=tag
            type=ref,suffix=-${{ github.run_number }},event=pr

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./debug
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.debug.outputs.tags }}
      # endregion debug

      # region utils
      - name: Get image meta
        id: utils
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/utils
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,suffix=-${{ github.run_number }},event=branch
            type=ref,suffix=-${{ github.run_number }},event=tag
            type=ref,suffix=-${{ github.run_number }},event=pr

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./utils
          platforms: linux/arm64
          tags: ${{ steps.utils.outputs.tags }}
      # endregion utils